package com.drd.trickytrialsbackport.registry;

import com.drd.trickytrialsbackport.TrickyTrialsBackport;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;

import java.util.function.Supplier;

public class ModSounds {
    public static Supplier<SoundEvent> APPLY_EFFECT_BAD_OMEN;
    public static Supplier<SoundEvent> APPLY_EFFECT_RAID_OMEN;
    public static Supplier<SoundEvent> APPLY_EFFECT_TRIAL_OMEN;
    public static Supplier<SoundEvent> CRAFTER_CRAFT;
    public static Supplier<SoundEvent> CRAFTER_FAIL;
    public static Supplier<SoundEvent> HEAVY_CORE_BREAK;
    public static Supplier<SoundEvent> HEAVY_CORE_STEP;
    public static Supplier<SoundEvent> HEAVY_CORE_FALL;
    public static Supplier<SoundEvent> HEAVY_CORE_PLACE;
    public static Supplier<SoundEvent> HEAVY_CORE_HIT;
    public static Supplier<SoundEvent> POLISHED_TUFF_BREAK;
    public static Supplier<SoundEvent> POLISHED_TUFF_STEP;
    public static Supplier<SoundEvent> POLISHED_TUFF_FALL;
    public static Supplier<SoundEvent> POLISHED_TUFF_PLACE;
    public static Supplier<SoundEvent> POLISHED_TUFF_HIT;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_ABOUT_TO_SPAWN_ITEM;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_AMBIENT;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_AMBIENT_OMINOUS;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_BREAK;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_CLOSE_SHUTTER;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_DETECT_PLAYER;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_EJECT_ITEM;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_FALL;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_HIT;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_OMINOUS_ACTIVATE;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_OPEN_SHUTTER;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_PLACE;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_SPAWN_ITEM;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_SPAWN_ITEM_BEGIN;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_SPAWN_MOB;
    public static Supplier<SoundEvent> TRIAL_SPAWNER_STEP;
    public static Supplier<SoundEvent> TUFF_BRICKS_BREAK;
    public static Supplier<SoundEvent> TUFF_BRICKS_STEP;
    public static Supplier<SoundEvent> TUFF_BRICKS_FALL;
    public static Supplier<SoundEvent> TUFF_BRICKS_PLACE;
    public static Supplier<SoundEvent> TUFF_BRICKS_HIT;
    public static Supplier<SoundEvent> BOGGED_AMBIENT;
    public static Supplier<SoundEvent> BOGGED_DEATH;
    public static Supplier<SoundEvent> BOGGED_HURT;
    public static Supplier<SoundEvent> BOGGED_SHEAR;
    public static Supplier<SoundEvent> BOGGED_STEP;
    public static Supplier<SoundEvent> BREEZE_CHARGE;
    public static Supplier<SoundEvent> BREEZE_DEATH;
    public static Supplier<SoundEvent> BREEZE_DEFLECT;
    public static Supplier<SoundEvent> BREEZE_HURT;
    public static Supplier<SoundEvent> BREEZE_IDLE_AIR;
    public static Supplier<SoundEvent> BREEZE_IDLE_GROUND;
    public static Supplier<SoundEvent> BREEZE_INHALE;
    public static Supplier<SoundEvent> BREEZE_JUMP;
    public static Supplier<SoundEvent> BREEZE_LAND;
    public static Supplier<SoundEvent> BREEZE_SHOOT;
    public static Supplier<SoundEvent> BREEZE_SLIDE;
    public static Supplier<SoundEvent> BREEZE_WHIRL;
    public static Supplier<SoundEvent> BREEZE_WIND_CHARGE_BURST;
    public static Supplier<SoundEvent> WIND_CHARGE_THROW;
    public static Supplier<SoundEvent> WIND_CHARGE_BURST;
    public static Supplier<SoundEvent> MACE_SMASH_AIR;
    public static Supplier<SoundEvent> MACE_SMASH_GROUND;
    public static Supplier<SoundEvent> MACE_SMASH_GROUND_HEAVY;
    public static Supplier<SoundEvent> MUSIC_DISC_CREATOR;
    public static Supplier<SoundEvent> MUSIC_DISC_CREATOR_MUSIC_BOX;
    public static Supplier<SoundEvent> MUSIC_DISC_PRECIPICE;

    public static void register() {
        RegistryHelper helper = RegistryHelper.getInstance();

        APPLY_EFFECT_BAD_OMEN = registerSound(helper, "event.mob_effect.bad_omen");
        APPLY_EFFECT_RAID_OMEN = registerSound(helper, "event.mob_effect.raid_omen");
        APPLY_EFFECT_TRIAL_OMEN = registerSound(helper, "event.mob_effect.trial_omen");
        CRAFTER_CRAFT = registerSound(helper, "block.crafter.craft");
        CRAFTER_FAIL = registerSound(helper, "block.crafter.fail");
        HEAVY_CORE_BREAK = registerSound(helper, "block.heavy_core.break");
        HEAVY_CORE_STEP = registerSound(helper, "block.heavy_core.step");
        HEAVY_CORE_FALL = registerSound(helper, "block.heavy_core.fall");
        HEAVY_CORE_PLACE = registerSound(helper, "block.heavy_core.place");
        HEAVY_CORE_HIT = registerSound(helper, "block.heavy_core.hit");
        POLISHED_TUFF_BREAK = registerSound(helper, "block.polished_tuff.break");
        POLISHED_TUFF_STEP = registerSound(helper, "block.polished_tuff.step");
        POLISHED_TUFF_FALL = registerSound(helper, "block.polished_tuff.fall");
        POLISHED_TUFF_PLACE = registerSound(helper, "block.polished_tuff.place");
        POLISHED_TUFF_HIT = registerSound(helper, "block.polished_tuff.hit");
        TRIAL_SPAWNER_ABOUT_TO_SPAWN_ITEM = registerSound(helper, "block.trial_spawner.about_to_spawn_item");
        TRIAL_SPAWNER_AMBIENT = registerSound(helper, "block.trial_spawner.ambient");
        TRIAL_SPAWNER_AMBIENT_OMINOUS = registerSound(helper, "block.trial_spawner.ambient_ominous");
        TRIAL_SPAWNER_BREAK = registerSound(helper, "block.trial_spawner.break");
        TRIAL_SPAWNER_CLOSE_SHUTTER = registerSound(helper, "block.trial_spawner.close_shutter");
        TRIAL_SPAWNER_DETECT_PLAYER = registerSound(helper, "block.trial_spawner.detect_player");
        TRIAL_SPAWNER_EJECT_ITEM = registerSound(helper, "block.trial_spawner.eject_item");
        TRIAL_SPAWNER_FALL = registerSound(helper, "block.trial_spawner.fall");
        TRIAL_SPAWNER_HIT = registerSound(helper, "block.trial_spawner.hit");
        TRIAL_SPAWNER_OMINOUS_ACTIVATE = registerSound(helper, "block.trial_spawner.ominous_activate");
        TRIAL_SPAWNER_OPEN_SHUTTER = registerSound(helper, "block.trial_spawner.open_shutter");
        TRIAL_SPAWNER_PLACE = registerSound(helper, "block.trial_spawner.place");
        TRIAL_SPAWNER_SPAWN_ITEM = registerSound(helper, "block.trial_spawner.spawn_item");
        TRIAL_SPAWNER_SPAWN_ITEM_BEGIN = registerSound(helper, "block.trial_spawner.spawn_item_begin");
        TRIAL_SPAWNER_SPAWN_MOB = registerSound(helper, "block.trial_spawner.spawn_mob");
        TRIAL_SPAWNER_STEP = registerSound(helper, "block.trial_spawner.step");
        TUFF_BRICKS_BREAK = registerSound(helper, "block.tuff_bricks.break");
        TUFF_BRICKS_STEP = registerSound(helper, "block.tuff_bricks.step");
        TUFF_BRICKS_FALL = registerSound(helper, "block.tuff_bricks.fall");
        TUFF_BRICKS_PLACE = registerSound(helper, "block.tuff_bricks.place");
        TUFF_BRICKS_HIT = registerSound(helper, "block.tuff_bricks.hit");
        BOGGED_AMBIENT = registerSound(helper, "entity.bogged.ambient");
        BOGGED_DEATH = registerSound(helper, "entity.bogged.death");
        BOGGED_HURT = registerSound(helper, "entity.bogged.hurt");
        BOGGED_SHEAR = registerSound(helper, "entity.bogged.shear");
        BOGGED_STEP = registerSound(helper, "entity.bogged.step");
        BREEZE_CHARGE = registerSound(helper, "entity.breeze.charge");
        BREEZE_DEATH = registerSound(helper, "entity.breeze.death");
        BREEZE_DEFLECT = registerSound(helper, "entity.breeze.deflect");
        BREEZE_HURT = registerSound(helper, "entity.breeze.hurt");
        BREEZE_IDLE_AIR = registerSound(helper, "entity.breeze.idle_air");
        BREEZE_IDLE_GROUND = registerSound(helper, "entity.breeze.idle_ground");
        BREEZE_INHALE = registerSound(helper, "entity.breeze.inhale");
        BREEZE_JUMP = registerSound(helper, "entity.breeze.jump");
        BREEZE_LAND = registerSound(helper, "entity.breeze.land");
        BREEZE_SHOOT = registerSound(helper, "entity.breeze.shoot");
        BREEZE_SLIDE = registerSound(helper, "entity.breeze.slide");
        BREEZE_WHIRL = registerSound(helper, "entity.breeze.whirl");
        BREEZE_WIND_CHARGE_BURST = registerSound(helper, "entity.breeze.wind_burst");
        WIND_CHARGE_THROW = registerSound(helper, "entity.wind_charge.throw");
        WIND_CHARGE_BURST = registerSound(helper, "entity.wind_charge.wind_burst");
        MACE_SMASH_AIR = registerSound(helper, "item.mace.smash_air");
        MACE_SMASH_GROUND = registerSound(helper, "item.mace.smash_ground");
        MACE_SMASH_GROUND_HEAVY = registerSound(helper, "item.mace.smash_ground_heavy");
        MUSIC_DISC_CREATOR = registerSound(helper, "music.disc.creator");
        MUSIC_DISC_CREATOR_MUSIC_BOX = registerSound(helper, "music.disc.creator_music_box");
        MUSIC_DISC_PRECIPICE = registerSound(helper, "music.disc.precipice");
    }

    private static Supplier<SoundEvent> registerSound(RegistryHelper helper, String name) {
        ResourceLocation id = new ResourceLocation(TrickyTrialsBackport.NAMESPACE, name);
        return helper.registerAuto(Registries.SOUND_EVENT, name, () -> SoundEvent.createVariableRangeEvent(id));
    }
}
